/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RouteoverviewLazyImport = createFileRoute('/route_overview')()
const ReportingLazyImport = createFileRoute('/reporting')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RouteoverviewLazyRoute = RouteoverviewLazyImport.update({
  id: '/route_overview',
  path: '/route_overview',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/route_overview.lazy').then((d) => d.Route),
)

const ReportingLazyRoute = ReportingLazyImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/reporting.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingLazyImport
      parentRoute: typeof rootRoute
    }
    '/route_overview': {
      id: '/route_overview'
      path: '/route_overview'
      fullPath: '/route_overview'
      preLoaderRoute: typeof RouteoverviewLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/reporting': typeof ReportingLazyRoute
  '/route_overview': typeof RouteoverviewLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/reporting': typeof ReportingLazyRoute
  '/route_overview': typeof RouteoverviewLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/reporting': typeof ReportingLazyRoute
  '/route_overview': typeof RouteoverviewLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reporting' | '/route_overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reporting' | '/route_overview'
  id: '__root__' | '/' | '/reporting' | '/route_overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ReportingLazyRoute: typeof ReportingLazyRoute
  RouteoverviewLazyRoute: typeof RouteoverviewLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ReportingLazyRoute: ReportingLazyRoute,
  RouteoverviewLazyRoute: RouteoverviewLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/reporting",
        "/route_overview"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/reporting": {
      "filePath": "reporting.lazy.tsx"
    },
    "/route_overview": {
      "filePath": "route_overview.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
